# Generated by Django 3.1.2 on 2020-10-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='usertype',
            field=models.CharField(blank=True, choices=[(0, 'Admin'), (1, 'User')], max_length=20, null=True),
        ),
    ]
