# Generated by Django 3.1.2 on 2020-10-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_profile_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='usertype',
            field=models.IntegerField(blank=True, choices=[(0, 'Admin'), (1, 'User')], null=True),
        ),
    ]
